version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the React project...
      - npm run build
  post_build:
    commands:
      - echo Build completed. Preparing to deploy to Elastic Beanstalk...
artifacts:
  files:
    - '**/*'
  base-directory: build
